insert into cliente (id, nome) values (1, 'Mercado do João');
insert into cliente (id, nome) values (2, 'Fale Mais');
insert into cliente (id, nome) values (3, 'Maria de Souza da Silva');
insert into cliente (id, nome) values (4, 'Gomes Inovação');
insert into cliente (id, nome) values (5, 'Diginess Software');
insert into cliente (id, nome) values (6, 'Bravospan Indústria de Alimentos');
insert into cliente (id, nome) values (7, 'Digiverse Seguros');
insert into cliente (id, nome) values (8, 'Jatz Logística');
insert into cliente (id, nome) values (9, 'Megamix Internet');
insert into cliente (id, nome) values (10, 'Tetrape Lotéricas');
insert into cliente (id, nome) values (11, 'Panishare Panificadora');
insert into cliente (id, nome) values (12, 'Dynacero Sites e Hospedagem');
insert into cliente (id, nome) values (13, 'Atlafire Livraria');
insert into cliente (id, nome) values (14, 'Brasilbug Cosméticos');
insert into cliente (id, nome) values (15, 'ClinicXS Cabeleireiros');
insert into cliente (id, nome) values (16, 'Voomia Telefonia');
insert into cliente (id, nome) values (17, 'Truzzy Modas e Acessórios');
insert into cliente (id, nome) values (18, 'Novabox Games e Informática');
insert into cliente (id, nome) values (19, 'Lumil Móveis para Escritório');
insert into cliente (id, nome) values (20, 'Renx Perfumaria');
insert into cliente (id, nome) values (21, 'Zaex Serviços Web');
insert into cliente (id, nome) values (22, 'Moncom Agência de Eventos');
insert into cliente (id, nome) values (23, 'Vifera Comércio de Plantas');
insert into cliente (id, nome) values (24, 'Detemp Serviços');
insert into cliente (id, nome) values (25, 'Plustie Petshop');
insert into cliente (id, nome) values (26, 'Tegrow Comércio Atacadista');
insert into cliente (id, nome) values (27, 'Jaway Espetos e Bebidas');
insert into cliente (id, nome) values (28, 'Zecom Consultoria em Redes');
