// <auto-generated />
namespace Senac.WebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class criacao_modelo_usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacao_modelo_usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251417570_criacao_modelo_usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
